export const TOUR = {
  AGENT: {
    DASHBOARD: {
      KPI_APPLICATION_STATUS: "agent-dashboard-kpi-application-status",
      KPI_DOCS_SIGNED: "agent-dashboard-kpi-docs-signed",
      KPI_OVERALL_PROGRESS: "agent-dashboard-kpi-overall-progress",
      KPI_MEMBER_SINCE: "agent-dashboard-kpi-member-since",
      CHECKLIST: "agent-dashboard-checklist",
      ACTION_ITEMS: "agent-dashboard-action-items",
    },
    DOCUMENTS: {
      ROOT: "agent-documents-root",
      SIGNED_BLOCK: "agent-documents-signed-block",
      UPLOADED_BLOCK: "agent-documents-uploaded-block",
      NDA: "agent-documents-nda",
      DEBT_ROLLUP: "agent-documents-debt-rollup",
      COMPLIANCE: "agent-documents-compliance",
      EO_UPLOAD: "agent-documents-eo-upload",
      GOV_ID_UPLOAD: "agent-documents-govid-upload",
      AML_UPLOAD: "agent-documents-aml-upload",
      DIRECT_DEPOSIT_UPLOAD: "agent-documents-dd-upload",
    },
    PROFILE: {
      ROOT: "agent-profile-root",
      PERSONAL: "agent-profile-personal",
      ADDRESS: "agent-profile-address",
      BACKGROUND: "agent-profile-background",
      SAVE_BUTTON: "agent-profile-save",
    },
    REQUESTS: {
      ROOT: "agent-requests-root",
      TAB_DRAFTS: "agent-requests-tab-drafts",
      TAB_AWAITING: "agent-requests-tab-awaiting",
      TAB_RETURNED: "agent-requests-tab-returned",
      NEW_REQUEST: "agent-requests-new",
      LIST: "agent-requests-list",
    },
    LICENSES: {
      ROOT: "agent-licenses-root",
      SUMMARY: "agent-licenses-summary",
      TABLE: "agent-licenses-table",
      ADD_BUTTON: "agent-licenses-add",
      SYNC_BUTTON: "agent-licenses-sync",
    },
    EO: {
      ROOT: "agent-eo-root",
      CURRENT: "agent-eo-current",
      UPLOAD: "agent-eo-upload",
      EXPIRATION: "agent-eo-expiration",
      PROVIDER: "agent-eo-provider",
    },
    BANK: {
      ROOT: "agent-bank-root",
      FORM: "agent-bank-form",
      ROUTING: "agent-bank-routing",
      ACCOUNT: "agent-bank-account",
      UPLOAD: "agent-bank-upload",
    },
    TRAININGS: {
      ROOT: "agent-trainings-root",
      GOV_ID: "agent-trainings-gov-id",
      AML: "agent-trainings-aml",
      CE_EXPIRATION: "agent-trainings-ce",
      UPLOAD_AREA: "agent-trainings-upload",
    },
    EMPLOYMENT: {
      ROOT: "agent-employment-root",
      HISTORY: "agent-employment-history",
      ADD_ENTRY: "agent-employment-add",
      GAPS_NOTE: "agent-employment-gaps",
    },
    DBA: {
      ROOT: "agent-dba-root",
      ENTITY_TYPE: "agent-dba-entity-type",
      ENTITY_DETAILS: "agent-dba-details",
      ARTICLES: "agent-dba-articles",
      OWNERS: "agent-dba-owners",
    },
    QUESTIONS: {
      ROOT: "agent-questions-root",
      PROGRESS: "agent-questions-progress",
      LIST: "agent-questions-list",
      EXPLANATION: "agent-questions-explanation",
    },
    CARRIERS: {
      ROOT: "agent-carriers-root",
      APPOINTED: "agent-carriers-appointed",
      PENDING: "agent-carriers-pending",
      REQUEST_NEW: "agent-carriers-request",
    },
    HIERARCHY: {
      ROOT: "agent-hierarchy-root",
      UPLINE: "agent-hierarchy-upline",
      DOWNLINE: "agent-hierarchy-downline",
      OVERRIDE_NOTE: "agent-hierarchy-override",
    },
  },
  ADMIN: {
    AGENTS_LIST: {
      HEADER: "admin-agents-header",
      KPI_TOTAL: "admin-agents-kpi-total",
      KPI_PENDING: "admin-agents-kpi-pending",
      KPI_IN_REVIEW: "admin-agents-kpi-in-review",
      KPI_ACTIVE: "admin-agents-kpi-active",
      TABS: "admin-agents-tabs",
      TABLE: "admin-agents-table",
    },
    AGENT_DETAIL: {
      HEADER: "admin-detail-header",
      TAB_PROFILE: "admin-detail-tab-profile",
      TAB_DOCUMENTS: "admin-detail-tab-documents",
      TAB_LICENSING: "admin-detail-tab-licensing",
      TAB_CARRIERS: "admin-detail-tab-carriers",
      TAB_CONTRACTING: "admin-detail-tab-contracting",
      TAB_QUESTIONS: "admin-detail-tab-questions",
      TAB_BUSINESS: "admin-detail-tab-business",
      STATUS_ACTIONS: "admin-detail-status-actions",
    },
    HCMS_DASHBOARD: {
      HEADER: "admin-hcms-dashboard-header",
      KPI_AGENTS: "admin-hcms-dashboard-kpi-agents",
      KPI_PENDING: "admin-hcms-dashboard-kpi-pending",
      KPI_IN_REVIEW: "admin-hcms-dashboard-kpi-in-review",
      KPI_ACTIVE: "admin-hcms-dashboard-kpi-active",
      KPI_ALERTS: "admin-hcms-dashboard-kpi-alerts",
      KPI_CARRIERS: "admin-hcms-dashboard-kpi-carriers",
      KPI_REQUESTS: "admin-hcms-dashboard-kpi-requests",
      QUICK_LINKS: "admin-hcms-dashboard-quick-links",
      QUICK_SEND_APP: "admin-hcms-dashboard-quick-send-app",
      APPLICATIONS_TABLE: "admin-hcms-dashboard-applications",
      ALERTS_TABLE: "admin-hcms-dashboard-alerts",
      STATUS_CHART: "admin-hcms-dashboard-status-chart",
      RECENT_ACTIVITY: "admin-hcms-dashboard-recent-activity",
    },
    CARRIERS: {
      HEADER: "admin-carriers-header",
      TABS: "admin-carriers-tabs",
      SEARCH: "admin-carriers-search",
      LIST: "admin-carriers-list",
      FIRST_ROW: "admin-carriers-first-row",
    },
    HIERARCHY: {
      HEADER: "admin-hierarchy-header",
      VIEW_TOGGLE: "admin-hierarchy-view-toggle",
      TREE: "admin-hierarchy-tree",
      TABLE: "admin-hierarchy-table",
    },
    HCMS_HIERARCHY: {
      CONTEXT_SET_TEAM: "admin-hcms-hierarchy-context-set-team",
      CONTEXT_CONVERT_AGENCY: "admin-hcms-hierarchy-context-convert-agency",
      NODE_DRAWER: "admin-hierarchy-node-drawer",
      NODE_DRAWER_CARRIERS: "admin-hierarchy-node-drawer-carriers",
      NODE_DRAWER_HIERARCHY: "admin-hierarchy-node-drawer-hierarchy",
    },
    CONTRACTING_OVERVIEW: {
      HEADER: "admin-contracting-overview-header",
      TABS: "admin-contracting-overview-tabs",
      MATRIX: "admin-contracting-overview-matrix",
      RESEND_CTA: "admin-contracting-overview-resend",
    },
    CONTRACTING_REQUESTS: {
      HEADER: "admin-contracting-requests-header",
      KPIS: "admin-contracting-requests-kpis",
      TABS: "admin-contracting-requests-tabs",
      TABLE: "admin-contracting-requests-table",
    },
    CONTRACTING_BANK: {
      HEADER: "admin-contracting-bank-header",
      SUMMARY: "admin-contracting-bank-summary",
      TABLE: "admin-contracting-bank-table",
      FILTER: "admin-contracting-bank-filter",
    },
    CONTRACTING_LICENSES: {
      HEADER: "admin-contracting-licenses-header",
      SUMMARY: "admin-contracting-licenses-summary",
      TABLE: "admin-contracting-licenses-table",
      FILTER: "admin-contracting-licenses-filter",
    },
    CONTRACTING_EO: {
      HEADER: "admin-contracting-eo-header",
      SUMMARY: "admin-contracting-eo-summary",
      TABLE: "admin-contracting-eo-table",
      FILTER: "admin-contracting-eo-filter",
    },
    CONTRACTING_TRAININGS: {
      HEADER: "admin-contracting-trainings-header",
      SUMMARY: "admin-contracting-trainings-summary",
      TABLE: "admin-contracting-trainings-table",
      FILTER: "admin-contracting-trainings-filter",
    },
    CONTRACTING_EMPLOYMENT: {
      HEADER: "admin-contracting-employment-header",
      SUMMARY: "admin-contracting-employment-summary",
      TABLE: "admin-contracting-employment-table",
      FILTER: "admin-contracting-employment-filter",
    },
    CONTRACTING_DBA: {
      HEADER: "admin-contracting-dba-header",
      SUMMARY: "admin-contracting-dba-summary",
      TABLE: "admin-contracting-dba-table",
      FILTER: "admin-contracting-dba-filter",
    },
    CONTRACTING_QUESTIONS: {
      HEADER: "admin-contracting-questions-header",
      SUMMARY: "admin-contracting-questions-summary",
      TABLE: "admin-contracting-questions-table",
      FILTER: "admin-contracting-questions-filter",
    },
  },
  FINANCE: {
    DASHBOARD: {
      HEADER: "finance-dashboard-header",
      PERIOD: "finance-dashboard-period",
      KPI_GRID: "finance-dashboard-kpi-grid",
      KPI_AP_SUBMITTED: "finance-dashboard-kpi-ap-submitted",
      KPI_AGENCY_OVERRIDE: "finance-dashboard-kpi-agency-override",
      WATERFALL: "finance-dashboard-waterfall",
      AREA_CHART: "finance-dashboard-area-chart",
    },
    REVENUE: {
      HEADER: "finance-revenue-header",
      PERIOD: "finance-revenue-period",
      KPI_GRID: "finance-revenue-kpi-grid",
      CHART: "finance-revenue-chart",
      CARRIERS_TABLE: "finance-revenue-carriers-table",
      AGENTS_TABLE: "finance-revenue-agents-table",
    },
    OVERRIDES: {
      HEADER: "finance-overrides-header",
      PERIOD: "finance-overrides-period",
      KPI_GRID: "finance-overrides-kpi-grid",
      SANKEY: "finance-overrides-sankey",
      EXPLAINER: "finance-overrides-explainer",
      HISTORY_TABLE: "finance-overrides-history-table",
    },
    TRANSACTIONS: {
      HEADER: "finance-transactions-header",
      PERIOD: "finance-transactions-period",
      SUMMARY: "finance-transactions-summary",
      TABS: "finance-transactions-tabs",
      TABLE: "finance-transactions-table",
    },
    CASHFLOW: { ROOT: "finance-cashflow-root" },
    CHARGEBACKS: { ROOT: "finance-chargebacks-root" },
    RECONCILIATION: { ROOT: "finance-reconciliation-root" },
    STATEMENTS: { ROOT: "finance-statements-root" },
    REPORTS: {
      HEADER: "finance-reports-header",
      PERIOD: "finance-reports-period",
      EXPORT_BUTTON: "finance-reports-export",
      REPORT_CARDS: "finance-reports-cards",
    },
  },
  FOUNDERS: {
    DASHBOARD: {
      HEADER: "founders-dashboard-header",
      PERIOD: "founders-dashboard-period",
      MANAGE_GOALS_BUTTON: "founders-dashboard-manage-goals-button",
      KPI_GRID: "founders-dashboard-kpi-grid",
      KPI_REVENUE_MTD: "founders-dashboard-kpi-revenue-mtd",
      KPI_REVENUE_YTD: "founders-dashboard-kpi-revenue-ytd",
      KPI_RUNWAY: "founders-dashboard-kpi-runway",
      KPI_ACTIVE_AGENTS: "founders-dashboard-kpi-active-agents",
      KPI_FOUNDER_PROFIT: "founders-dashboard-kpi-founder-profit",
      KPI_CASH_POSITION: "founders-dashboard-kpi-cash-position",
      AT_A_GLANCE: "founders-dashboard-at-a-glance",
      TOP_PERFORMERS: "founders-dashboard-top-performers",
      ATTENTION: "founders-dashboard-attention",
      QUARTERLY_GOALS: "founders-dashboard-quarterly-goals",
      ONBOARDING_PIPELINE: "founders-dashboard-onboarding-pipeline",
      OPERATIONS_HEALTH: "founders-dashboard-operations-health",
      CARRIER_VELOCITY: "founders-dashboard-carrier-velocity",
      COMPLIANCE: "founders-dashboard-compliance",
      CASH_FLOW: "founders-dashboard-cash-flow",
      RECENT_ACTIVITY: "founders-dashboard-recent-activity",
      AREA_CHART: "founders-dashboard-area-chart",
      BAR_CHART: "founders-dashboard-bar-chart",
      QUORUM_QUEUE: "founders-dashboard-quorum-queue",
    },
    REVENUE: {
      HEADER: "founders-revenue-header",
      PERIOD: "founders-revenue-period",
      KPI_GRID: "founders-revenue-kpi-grid",
      WATERFALL: "founders-revenue-waterfall",
      SANKEY: "founders-revenue-sankey",
      CARRIERS_TABLE: "founders-revenue-carriers-table",
      AGENTS_TABLE: "founders-revenue-agents-table",
      LEAD_REVENUE_TABLE: "founders-revenue-lead-revenue-table",
    },
    HIERARCHY: {
      ROOT: "founders-hierarchy-root",
    },
    GROWTH: {
      HEADER: "founders-growth-header",
      KPI_GRID: "founders-growth-kpi-grid",
      FUNNEL_CHART: "founders-growth-funnel-chart",
      HIRING_TREND: "founders-growth-hiring-trend",
      TEAMS_TABLE: "founders-growth-teams-table",
      TOP_PERFORMERS: "founders-growth-top-performers",
    },
    PROFIT_SPLIT: {
      HEADER: "founders-profit-split-header",
      PERIOD: "founders-profit-split-period",
      KPI_GRID: "founders-profit-split-kpi-grid",
      SPLIT_CARD: "founders-profit-split-split-card",
      TIMELINE_CHART: "founders-profit-split-timeline-chart",
      LEDGER_TABLE: "founders-profit-split-ledger-table",
      ADD_DEPOSIT_BUTTON: "founders-profit-split-add-deposit-button",
    },
    ACCESS: {
      HEADER: "founders-access-header",
      TABS: "founders-access-tabs",
      PENDING_TABLE: "founders-access-pending-table",
      MEMBERS_TABLE: "founders-access-members-table",
      LOUNGE_MATRIX: "founders-access-lounge-matrix",
      INVITE_BUTTON: "founders-access-invite-button",
      KPI_GRID: "founders-access-kpi-grid",
      IMPERSONATE: "founders-access-impersonate",
    },
    VIEWAS: {
      HEADER: "founders-viewas-header",
      ACTIVE_BANNER: "founders-viewas-active-banner",
      SEARCH: "founders-viewas-search",
      TARGETS_TABLE: "founders-viewas-targets-table",
      HISTORY_TABLE: "founders-viewas-history-table",
    },
    SETTINGS: {
      HEADER: "founders-settings-header",
      NOTIFICATIONS: "founders-settings-notifications",
      FEATURE_FLAGS: "founders-settings-feature-flags",
      PLATINUM_TOGGLE: "founders-settings-platinum-toggle",
      EXPORT_BUTTON: "founders-settings-export-button",
      EXPORT_CARD: "founders-settings-export-card",
      SYSTEM_CONSTANTS: "founders-settings-system-constants",
      SESSIONS: "founders-settings-sessions",
    },
    COMMAND_PALETTE: {
      ROOT: "founders-command-palette-root",
      NAV_GROUP: "founders-command-palette-nav-group",
      CROSS_LOUNGE_GROUP: "founders-command-palette-cross-lounge-group",
      ACTIONS_GROUP: "founders-command-palette-actions-group",
    },
    BOOK: {
      HEADER: "founders-book-header",
      KPI_GRID: "founders-book-kpi-grid",
      TEAMS_TABLE: "founders-book-teams-table",
      DRAWER_TEAM: "founders-book-drawer-team",
      DRAWER_AGENT: "founders-book-drawer-agent",
      DRAWER_CLIENT: "founders-book-drawer-client",
    },
    TEAM_PERF: {
      HEADER: "founders-team-perf-header",
      KPI_GRID: "founders-team-perf-kpi-grid",
      TABS: "founders-team-perf-tabs",
      COMPARISON_CHART: "founders-team-perf-comparison-chart",
      TEAM_CARDS: "founders-team-perf-team-cards",
      AGENT_RANKINGS_TABLE: "founders-team-perf-agent-rankings-table",
      TRENDS_CHART: "founders-team-perf-trends-chart",
      TEAM_DETAILS: "founders-team-perf-team-details",
    },
    LEAD_DIST: {
      HEADER: "founders-lead-dist-header",
      KPI_GRID: "founders-lead-dist-kpi-grid",
      IMPORT_CARD: "founders-lead-dist-import-card",
      DISTRIBUTE_CARD: "founders-lead-dist-distribute-card",
      TABS: "founders-lead-dist-tabs",
      POOL_TABLE: "founders-lead-dist-pool-table",
      LIVE_INDICATOR: "founders-lead-dist-live-indicator",
      DRAWER_LEAD: "founders-lead-dist-drawer-lead",
      DISTRIBUTION_HISTORY: "founders-lead-dist-distribution-history",
    },
    AGENCY_MGMT: {
      HEADER: "founders-agency-mgmt-header",
      KPI_GRID: "founders-agency-mgmt-kpi-grid",
      TABS: "founders-agency-mgmt-tabs",
      AGENCY_TREE: "founders-agency-mgmt-agency-tree",
      AGENCY_DETAIL: "founders-agency-mgmt-agency-detail",
      CARRIER_DIRECTORY: "founders-agency-mgmt-carrier-directory",
      AGENCY_CONTRACTS: "founders-agency-mgmt-agency-contracts",
      ENTITY_ROSTER: "founders-agency-mgmt-entity-roster",
      ENTITY_CHART: "founders-agency-mgmt-entity-chart",
      FORMATION_GUIDE: "founders-agency-mgmt-formation-guide",
      ADD_CARRIER_BUTTON: "founders-agency-mgmt-add-carrier",
      NEW_AGENCY_BUTTON: "founders-agency-mgmt-new-agency",
      QUICK_NAME_BUTTON: "founders-agency-mgmt-quick-name",
    },
  },
  SHELL: {
    SIDEBAR: "hcms-shell-sidebar",
    TOUR_BUTTON: "hcms-shell-tour-button",
    APP_SWITCHER: "hcms-shell-app-switcher",
    THEME_TOGGLE: "hcms-shell-theme-toggle",
    NOTIFICATIONS: "hcms-shell-notifications",
    USER_MENU: "hcms-shell-user-menu",
  },
} as const;

export function tourAttr(id: string | undefined) {
  return id ? ({ "data-tour-id": id } as const) : ({} as const);
}

export function tourSelector(id: string) {
  return `[data-tour-id="${id}"]`;
}
