import { pgTable, varchar, uuid, timestamp, text, boolean, integer } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";

export const agentProfiles = pgTable("agent_profiles", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id"),
  firstName: varchar("first_name", { length: 100 }),
  lastName: varchar("last_name", { length: 100 }),
  dateOfBirth: varchar("date_of_birth", { length: 20 }),
  phone: varchar("phone", { length: 20 }),
  email: varchar("email", { length: 255 }),
  streetAddress: varchar("street_address", { length: 255 }),
  city: varchar("city", { length: 100 }),
  state: varchar("state", { length: 2 }),
  zipCode: varchar("zip_code", { length: 10 }),
  title: varchar("title", { length: 100 }),
  companyName: varchar("company_name", { length: 200 }),
  yearsExperience: varchar("years_experience", { length: 20 }),
  previousAgency: varchar("previous_agency", { length: 200 }),
  // Self-reported commission level at the applicant's existing IMO (Discord
  // apply step) — context for the approver, not their Gold Coast placement.
  priorImoCommissionLevel: integer("current_commission_level_at_prior_imo"),
  npn: varchar("npn", { length: 20 }),
  isLicensed: boolean("is_licensed").default(false),
  licenseNumber: varchar("license_number", { length: 50 }),
  licensedStates: text("licensed_states"),
  eoProvider: varchar("eo_provider", { length: 200 }),
  eoPolicyNumber: varchar("eo_policy_number", { length: 50 }),
  eoEffectiveDate: varchar("eo_effective_date", { length: 20 }),
  eoExpirationDate: varchar("eo_expiration_date", { length: 20 }),
  eoCoverageAmount: varchar("eo_coverage_amount", { length: 50 }),
  websiteUrl: varchar("website_url", { length: 500 }),
  linkedinUrl: varchar("linkedin_url", { length: 500 }),
  ssnEncrypted: text("ssn_encrypted"),
  bankName: varchar("bank_name", { length: 200 }),
  bankAccountType: varchar("bank_account_type", { length: 20 }),
  routingNumberEncrypted: text("routing_number_encrypted"),
  accountNumberEncrypted: text("account_number_encrypted"),
  onboardingType: varchar("onboarding_type", { length: 30 }).default("standard"),
  onboardingStep: integer("onboarding_step").default(0),
  onboardingCompletedAt: timestamp("onboarding_completed_at"),
  onboardingToken: varchar("onboarding_token", { length: 255 }),
  onboardingTokenExpiresAt: timestamp("onboarding_token_expires_at"),
  approvalStatus: varchar("approval_status", { length: 30 }).default("pending_review"),
  approvedBy: uuid("approved_by"),
  approvedAt: timestamp("approved_at"),
  rejectionReason: text("rejection_reason"),
  hasFelony: boolean("has_felony").default(false),
  felonyDetails: text("felony_details"),
  hasBankruptcy: boolean("has_bankruptcy").default(false),
  bankruptcyDetails: text("bankruptcy_details"),
  docusignNdaEnvelopeId: varchar("docusign_nda_envelope_id", { length: 100 }),
  docusignNdaSigned: boolean("docusign_nda_signed").default(false),
  docusignNdaSignedAt: timestamp("docusign_nda_signed_at"),
  docusignNdaS3Key: text("docusign_nda_s3_key"),
  docusignDebtRollupEnvelopeId: varchar("docusign_debt_rollup_envelope_id", { length: 100 }),
  docusignDebtRollupSigned: boolean("docusign_debt_rollup_signed").default(false),
  docusignDebtRollupSignedAt: timestamp("docusign_debt_rollup_signed_at"),
  docusignDebtRollupS3Key: text("docusign_debt_rollup_s3_key"),
  docusignComplianceEnvelopeId: varchar("docusign_compliance_envelope_id", { length: 100 }),
  docusignComplianceSigned: boolean("docusign_compliance_signed").default(false),
  docusignComplianceSignedAt: timestamp("docusign_compliance_signed_at"),
  docusignComplianceS3Key: text("docusign_compliance_s3_key"),
  eoCertificateS3Key: text("eo_certificate_s3_key"),
  driversLicenseS3Key: text("drivers_license_s3_key"),
  directDepositFormS3Key: text("direct_deposit_form_s3_key"),
  amlCertificateS3Key: text("aml_certificate_s3_key"),
  articlesS3Key: text("articles_s3_key"),
  backgroundAnswers: text("background_answers"),
  // Business entity
  dbaType: varchar("dba_type", { length: 30 }),
  ein: varchar("ein", { length: 20 }),
  companyType: varchar("company_type", { length: 50 }),
  stateOfInc: varchar("state_of_inc", { length: 2 }),
  dbaName: varchar("dba_name", { length: 200 }),
  licenseType: varchar("license_type", { length: 30 }),
  formationDate: varchar("formation_date", { length: 20 }),
  businessEmail: varchar("business_email", { length: 255 }),
  businessPhone: varchar("business_phone", { length: 20 }),
  businessFax: varchar("business_fax", { length: 20 }),
  businessWebsite: varchar("business_website", { length: 255 }),
  businessStreet: varchar("business_street", { length: 255 }),
  businessUnit: varchar("business_unit", { length: 100 }),
  businessCity: varchar("business_city", { length: 100 }),
  businessState: varchar("business_state", { length: 2 }),
  businessZip: varchar("business_zip", { length: 10 }),
  mailingStreet: varchar("mailing_street", { length: 255 }),
  mailingUnit: varchar("mailing_unit", { length: 100 }),
  mailingCity: varchar("mailing_city", { length: 100 }),
  mailingState: varchar("mailing_state", { length: 2 }),
  mailingZip: varchar("mailing_zip", { length: 10 }),
  mailingSameAsBusiness: boolean("mailing_same_as_business").default(false),
  ownersJson: text("owners_json"),
  drlpJson: text("drlp_json"),
  beneficiaryJson: text("beneficiary_json"),
  ceExpirationDate: varchar("ce_expiration_date", { length: 20 }),
  agreedToTerms: boolean("agreed_to_terms").default(false),
  agreedToPrivacy: boolean("agreed_to_privacy").default(false),
  consentedAt: timestamp("consented_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const userLoungeAccess = pgTable("user_lounge_access", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id").notNull(),
  feature: varchar("feature", { length: 50 }).notNull(),
  enabled: boolean("enabled").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertAgentProfileSchema = createInsertSchema(agentProfiles).omit({ id: true, createdAt: true, updatedAt: true });
export type AgentProfile = typeof agentProfiles.$inferSelect;
