import { pgTable, varchar, uuid, timestamp, text, boolean, index } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";

export const complianceFlags = pgTable("compliance_flags", {
  id: uuid("id").defaultRandom().primaryKey(),
  agentUserId: uuid("agent_user_id"),
  flagType: varchar("flag_type", { length: 50 }).notNull(),
  severity: varchar("severity", { length: 20 }).notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  description: text("description"),
  relatedTable: varchar("related_table", { length: 50 }),
  relatedId: varchar("related_id", { length: 100 }),
  dueDate: timestamp("due_date"),
  status: varchar("status", { length: 20 }).default("open"),
  resolvedAt: timestamp("resolved_at"),
  resolvedBy: uuid("resolved_by"),
  resolvedNotes: text("resolved_notes"),
  autoGenerated: boolean("auto_generated").default(true),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [index("idx_flags_agent").on(t.agentUserId), index("idx_flags_severity").on(t.severity), index("idx_flags_status").on(t.status)]);

export const insertComplianceFlagSchema = createInsertSchema(complianceFlags).omit({ id: true, createdAt: true, updatedAt: true });
export type ComplianceFlag = typeof complianceFlags.$inferSelect;

export const FLAG_TYPES = ["license_expiring", "eo_expiring", "missing_state_license", "contracting_stalled", "production_without_appointment", "agent_inactive", "document_unsigned", "ce_credits_due"] as const;
export const SEVERITY_LEVELS = ["info", "warning", "critical", "blocker"] as const;
